import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>Stripe Payment Demo</title>
      </head>
      <body className={inter.className}>
        <div className="h-screen w-screen flex justify-center items-center bg-slate-600">
          {children}
        </div>
      </body>
    </html>
  );
}
